project:
  type: website

website:
  title: "QMIR 2026"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
      - href: installation.qmd
        text: Installation Guide
  repo-url: "https://github.com/qmir-2026/qmir-2026.github.io"
  repo-actions: [source, issue]
  reader-mode: false
  page-footer:
    left: |
      © 2026 Tristan Muno  
      Licensed under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with  ♥ and [Quarto](https://quarto.org/)

freeze: true

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    include-in-header:
      text:
        <meta name="robots" content="noindex">

bibliography: references.bib
biblio-style: apsr

filters:
  - quarto-ext/fontawesome